server:
  port: 7000
spring:
  application:
    name: api-gateway
  config:
    import: optional:configserver:http://localhost:8888
  cloud:
    gateway:
      routes:
        - id: products
          uri: lb://SERVICE
          predicates: 
            - Path=/api/products/**
        - id: hello
          uri: lb://SERVICE
          predicates: 
            - Path=/api/hello
        - id: order
          uri: lb://ORDER
          predicates:
            - Path= /api/orders/**
        - id: inventory
          uri: lb://INVENTORY-SERVICE
          predicates:
            - Path= /api/inventory/**
        - id: payment
          uri: lb://PAYMENT
          predicates:
            - Path= /api/inventory/**
        - id: users
          uri: lb://AUTHSERVICE
          predicates:
            - Path= /api/users/**

