server:
  port: 6001
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/orderdb
    username: root
    password: root
  application:
    name: order
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

eureka:
  client:
    enabled: true
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka