server:
  port: 6001
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/orderdb
    username: root
    password: root
  application:
    name: order
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update