server:
  port: 6004
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/paymentdb
    username: root
    password: root
  application:
    name: payment
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

