server:
  port: 6002
spring:
  application:
    name: inventory-service
  data:
    mongodb:
        host: localhost
        port: 27017
        database: inventorydb
        username: root
        password: generic
        authentication-database: admin
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration


eureka:
  client:
    enabled: true
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka